services:
  nginx:
    build:
      context: nginx
      dockerfile: dockerfile
    image: public.ecr.aws/xxxxxxxx/peter_tester
    container_name: nginx

  php-fpm:
    build:
      context: php
      dockerfile: dockerfile
    image: public.ecr.aws/xxxxxxxx/php-fpm
    container_name: php-fpm
