services:
  nginx:
    build:
      context: nginx
      dockerfile: dockerfile
    image: public.ecr.aws/w3l0w0b0/nginx
    container_name: nginx
    env_file:
      - nginx/.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      
  php-fpm:
    build:
      context: php-fpm
      dockerfile: dockerfile
    image: public.ecr.aws/w3l0w0b0/php-fpm
    container_name: php-fpm
