services:
  nginx:
    build:
      context: nginx
      dockerfile: dockerfile
    image: ${{ DEPLOYMENT_GROUP_NAME }}
    container_name: nginx

  php-fpm:
    build:
      context: php-fpm
      dockerfile: dockerfile
    image: ${{ DEPLOYMENT_GROUP_NAME }}
    container_name: php-fpm
