services:
  nginx:
    build:
      context: nginx
      dockerfile: dockerfile
    image: public.ecr.aws/w3l0w0b0/nginx
    container_name: nginx

  php-fpm:
    build:
      context: php-fpm
      dockerfile: dockerfile
    image: public.ecr.aws/w3l0w0b0/php-fpm
    container_name: php-fpm
