# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ls -l 
        run: ls -l 

