name: dev 環境 build-test-deploy
###
on:
  push:
    branches: [ "main" ]

jobs:
  # build:
  #   uses: p81061473525/argocdtest/.github/workflows/ecr_ci.yaml@main
  #   secrets:
  #     AWS_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
  #  needs: build
    uses: p81061473525/argocdtest/.github/workflows/deploy-argocd.yaml@main
  # secrets:
  #   AWS_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #   AWS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
