# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: test aws 
        run: aws ec2 describe-instances >> a 
        
      - name: ls -l 
        run: ls -l 
        
      - name: install aws
        run: sudo apt install awscli -y 
        
      - name: install docker  
        run: sudo apt install docker -y 

      - name: check aws and docker command
        run: |
          aws --version 
          docker --version
          
      - name: systemctl restart docker 
        run: sudo systemctl restart docker 
        
      - name: dokcer build 
        run: sudo docker build -t peter .

      - name: dokcer imaegs
        run: sudo docker images

      - name: login ECR
        run: sudo aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 394797297203.dkr.ecr.ap-northeast-1.amazonaws.com

      - name: docker tag nginx_test:latest 394797297203.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_test:latest
        run: sudo docker tag peter:latest 394797297203.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_test:latest

      - name: docker push 394797297203.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_test:latest
        run: sudo docker push 394797297203.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_test:latest 
